spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    properties:
     hibernate:
      default_schema: realt
  datasource:
    url: jdbc:postgresql://db:5432/flat?currentSchema=realt
    username: realtv1
    password: HW)!WD%ey*@t)<C?dbxn2W-
    driverClassName: org.postgresql.Driver
  sql:
    init:
     platform: postgres
  main:
   banner-mode: off