spring:
  mail:
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
        smtp.starttls.enable: true
app:
  jwt:
    secret: NDQ1ZjAzNjQtMzViZi00MDRjLTljZjQtNjNjYWIyZTU5ZDYw
    issuer: ITAcademy
  mail:
    properties:
      subject: "please, confirm your email address in our service"
      text-prefix: "Thank you for creating your SearchFlats Account. To complete your registration, click the link below:"
      text-postfix: "With best regards, SearchFlats Technical Support"
